site_name: Guggy Docs
site_favicon: favicon.ico
theme: yeti
extra_css:
  - test.css
pages:
- Welcome: index.md
- Android: android.md
- iOS (Swift): ios-swift.md
- JS SDK: js-sdk.md
- Rest API: rest-api.md